services:
  jekyll:
    container_name: blog
    image: blog-jekyll
    platform: linux/amd64
    build: 
      context: . 
    volumes:
      - .:/site
    ports:
      - "4000:4000"
    working_dir: /site 